olist_quality:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST', 'localhost') }}"
      port: "{{ env_var('DB_PORT', '5433') | int }}"
      dbname: "{{ env_var('DB_NAME', 'olist') }}"
      user: "{{ env_var('DB_USER', 'olist_user') }}"
      password: "{{ env_var('DB_PASSWORD', 'olist_pass') }}"
      schema: public
      threads: 4