version: "3.9"
services:
  scheduler:
    volumes:
      - ../ingestion:/usr/local/airflow/ingestion
      - ../monitoring:/usr/local/airflow/monitoring
      - ../alerting:/usr/local/airflow/alerting
      - ../dbt_project:/usr/local/airflow/dbt_project
      - ../data:/usr/local/airflow/data
      - ../.env:/usr/local/airflow/.env
  webserver:
    volumes:
      - ../ingestion:/usr/local/airflow/ingestion
      - ../monitoring:/usr/local/airflow/monitoring
      - ../alerting:/usr/local/airflow/alerting
      - ../dbt_project:/usr/local/airflow/dbt_project
      - ../data:/usr/local/airflow/data
      - ../.env:/usr/local/airflow/.env
  triggerer:
    volumes:
      - ../ingestion:/usr/local/airflow/ingestion
      - ../monitoring:/usr/local/airflow/monitoring
      - ../alerting:/usr/local/airflow/alerting
      - ../dbt_project:/usr/local/airflow/dbt_project
      - ../data:/usr/local/airflow/data
      - ../.env:/usr/local/airflow/.env